DELETE FROM ESTUDIO;
DELETE FROM TELEFONO_VETERINARIA;
DELETE FROM VETERINARIA;
DELETE FROM HABLA;
DELETE FROM IDIOMA;
DELETE FROM CORREO_ELECTRONICO;
DELETE FROM COLEGIADO;


DROP TABLE CUENTA;
DROP TABLE ADMINISTRA;
DROP TABLE INTEGRANTE;
DROP TABLE ACUMULADO;
DROP TABLE DIRECTIVA;
DROP TABLE TELEFONO;
DROP TABLE HABLA;
DROP TABLE IDIOMA;
DROP TABLE ADQUIERE;
DROP TABLE CERTIFICADO;
DROP TABLE ESTUDIO;
DROP TABLE TELEFONO_VETERINARIA;
DROP TABLE VETERINARIA;
DROP TABLE PAGO;
DROP TABLE COLEGIATURA;
DROP TABLE CORREO_ELECTRONICO;
DROP TABLE COLEGIADO;